# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Test CI

on:
  push:
    branches: [ v0.1.3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 'Step 1: Checkout Code'
      uses: actions/checkout@v2

    - name: 'Step 2: Use Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Step 3: Install'
      run: yarn install

    - name: 'Step 4: Build code'
      run: yarn build:test --if-present

    - name: 'Step 5: Deploy to test server'
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TEST_KEY }}
        REMOTE_PORT: ${{ secrets.TEST_PORT }}
        REMOTE_HOST: ${{ secrets.TEST_HOST }}
        REMOTE_USER: ${{ secrets.TEST_USER }}
        TARGET: ${{ secrets.TEST_TARGET }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist/"
